steps:
- id: download
  name: 'gcr.io/$PROJECT_ID/psnextv1-builder'
  entrypoint: bash
  args:
    - -c
    - |
      node --version
      docker --version
      kubectl version --client
      gcloud container clusters get-credentials --project="$PROJECT_ID" --region="$_CLOUDSDK_COMPUTE_ZONE" "$_CLOUDSDK_CONTAINER_CLUSTER"
      pwd
      gsutil cp gs://cache-psnext-v1-$BRANCH_NAME/*.tar.gz .
      git fetch --depth=10
      git log --pretty=oneline
      test -f ./nm.tar.gz && tar xzf nm.tar.gz
      test -f ./dist.tar.gz && tar xzf dist.tar.gz
      cat ./node_modules/LAST_BUILD_COMMIT_SHA > LAST_BUILD_COMMIT_SHA
      # save the commit info & build date
      NOW=$(date +"%Y-%m-%d %T")
      echo "{\"branch\":\"$BRANCH_NAME\", \"commit\":\"$COMMIT_SHA\", \"repo\":\"$REPO_NAME\", \"buildtime\":\"$$NOW\", \"buildid\":\"$BUILD_ID\"}" > _buildinfo.js
      cat _buildinfo.js
      npm i --quiet --no-progress
# step 1  build
- id: build
  waitFor:
    - download
  name: 'gcr.io/$PROJECT_ID/psnextv1-builder'
  entrypoint: bash
  args:
    - -c
    - |
      npm run nx -- affected:build --base=$(cat LAST_BUILD_COMMIT_SHA)
# setp 2 build image
- id: deploy
  waitFor:
    - build
  name: 'gcr.io/$PROJECT_ID/psnextv1-builder'
  entrypoint: bash
  args:
    - -c
    - |
      npm run nx -- affected --target=build-docker --base=$(cat LAST_BUILD_COMMIT_SHA) --args="--projectid=$PROJECT_ID --branch=$BRANCH_NAME --sha=$COMMIT_SHA"
      npm run nx -- affected --target=k8s-deploy --base=$(cat LAST_BUILD_COMMIT_SHA) --args="--projectid=$PROJECT_ID --branch=$BRANCH_NAME --sha=$COMMIT_SHA"
# step 2 cache
- id: cache
  waitFor:
    - build
  name: 'gcr.io/$PROJECT_ID/psnextv1-builder'
  entrypoint: bash
  args:
    - -c
    - |
      echo -n $COMMIT_SHA > /workspace/node_modules/LAST_BUILD_COMMIT_SHA
      tar czf nm.tar.gz ./node_modules
      tar czf dist.tar.gz ./dist
      echo 'generated cache files.'
      gsutil cp *.tar.gz gs://cache-psnext-v1-$BRANCH_NAME/
timeout: 3600s
# options:
#   substitution_option: 'ALLOW_LOOSE'
# substitutions:
#   _LAST_BUILD_COMMIT_SHA: unknown
