steps:
# step 0 Upload to Cloud Storage.
- id: "Download"
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', 'gs://cache-psnext-v1-$BRANCH_NAME/nm.tar.gz', 'nm.tar.gz']
# step 1  build
- id: "Build"
  name: 'gcr.io/$PROJECT_ID/psnextv1-builder'
  entrypoint: bash
  args:
    - -c
    - |
      pwd
      tar xzf nm.tar.gz
      ls ./node_modules
      # save the commit info & build date
      NOW=$(date +"%Y-%m-%d %T")
      echo "{\"branch\":\"$BRANCH_NAME\", \"commit\":\"$COMMIT_SHA\", \"repo\":\"$REPO_NAME\", \"buildtime\":\"$$NOW\", \"buildid\":\"$BUILD_ID\"}" > _buildinfo.js
      cat _buildinfo.js
      node --version
      docker --version
      npm i --quiet --no-progress
      npm run nx -- build
      tar czf nm.tar.gz ./node_modules
      tar czf dist.tar.gz ./dist
# step 2 Upload node_modules to Cloud Storage.
- id: "Upload NM"
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', 'nm.tar.gz', 'gs://cache-psnext-v1-$BRANCH_NAME/nm.tar.gz']
# step 3 Upload dist to Cloud Storage.
- id: "Upload D"
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', 'dist.tar.gz', 'gs://cache-psnext-v1-$BRANCH_NAME/dist.tar.gz']
timeout: 3600s
