steps:
# step 1  build
- id: "Build"
  name: 'gcr.io/$PROJECT_ID/psnextv1-builder'
  entrypoint: bash
  args:
    - -c
    - |
      pwd
      # save the commit info & build date
      NOW=$(date +"%Y-%m-%d %T")
      echo "{\"branch\":\"$BRANCH_NAME\", \"commit\":\"$COMMIT_SHA\", \"repo\":\"$REPO_NAME\", \"buildtime\":\"$$NOW\", \"buildid\":\"$BUILD_ID\"}" > _buildinfo.js
      cat _buildinfo.js
      node --version
      docker --version
      npm i
      npm run nx -- build
# step 2 Upload to Cloud Storage.
- id: "Upload1"
  name: 'gcr.io/cloud-builders/gcs-uploader'
  args:
    - '--location=gs://cache-psnext-v1-$BRANCH_NAME/nm'
    - '--dir=./node_modules'
- id: "Upload2"
  name: 'gcr.io/cloud-builders/gcs-uploader'
  args:
    - '--location=gs://cache-psnext-v1-$BRANCH_NAME/dist'
    - '--dir=./dist'
timeout: 3600s
