apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  template:
    spec:
      containers:
      - name: psni-hackathon-app
        resources:
          limits:
            memory: 512Mi
